
workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - sayedrizwan.bsef18@iba-suk.edu.pk
  default-workflow-(copy):
    name: Default Workflow (Copy)
    max_build_duration: 60
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - sayedrizwan.bsef18@iba-suk.edu.pk
